Create pull_request_test
hessllab/HW_0 pull request #1
Opened 2019-07-22 21:55 UTC by MorganLeef

2019-07-28 17:11 UTC, ahessl commented
Hi Morgan.  Yes, you would need to create your own branch before generating the pull request.  I am trying to sort out how I work with that request.  Did you submit a new file?

2019-07-29 00:21 UTC, MorganLeef commented
I did create a new file, I just copied the original README, renamed it, and created a fork. I think you should have permission to edit it, I checked the box that says "Allow edits from maintainers". Is there something else I need to change?

2019-07-30 19:10 UTC, ahessl commented
What is the name of the branch?  patch-1
??

2019-07-30 19:13 UTC, ahessl reviewed
Thanks for entertaining me as I figure this out Morgan.
This is where I could ask for a change.

2019-07-30 19:15 UTC, ahessl commented on pull_request_test
> +Github says I do not have "write" access to this file,so it is creating another branch. Hopefully that's what you were going for.
Or it seems I can leave a comment regarding a particular line.

2019-07-30 19:17 UTC, ahessl requested changes

2019-07-30 19:17 UTC, ahessl commented on pull_request_test
> +Github says I do not have "write" access to this file,so it is creating another branch. Hopefully that's what you were going for.
Or possibly start a review that involves multiple comments at different lines

2019-07-30 19:17 UTC, ahessl commented on pull_request_test
> +Github says I do not have "write" access to this file,so it is creating another branch. Hopefully that's what you were going for.
Another comment here.

2019-07-30 19:17 UTC, ahessl commented
Wow this is going to be a little bit rough at first!!!

2019-08-25 20:53 UTC, ahessl commented
Thanks Morgan!  This helped me a lot.

2019-08-25 20:53 UTC, closed without merging